QubesOS/qubes-app-linux-split-gpg

qubes.Gpg.service

Enigmail will soon cease to work with gpg 1.x and will work only with gpg 2.0 or higher.

Use gpg2 by default

---

debian/control

Without it, it fails to create the prompt in the backend VM that allows the user to authorize access to the keys to a frontend VM.

Split GPG depends on zenity for user prompts

---

qubes.GpgImportKey.service

There was an inconsistency in gpg versions between 'qubes.Gpg.service' and 'qubes.GpgImportKey.service'
Fixes https://github.com/QubesOS/qubes-issues/issues/1874

Use gpg2 in GpgImportKey

---

gpg-client-wrapper

I admit I don't know all the implications of proposed change, and I haven't tested it very thoroughly yet, but with this change to qubes-gpg-client-wrapper both https://www.passwordstore.org/ and https://keyringer.pw/ seem to work when made to see it as the gpg binary to use.

Attempt at making GPG password managers to work

---

.gitignore
.travis.yml
Makefile
README.md
debian/control
debian/qubes-gpg-split.install
doc/Makefile
doc/qubes-gpg-client-wrapper.rst
doc/qubes-gpg-client.rst
doc/qubes-gpg-import-key.rst
rpm_spec/gpg-split.spec

Added a basic README (pulled from the first paragraph of the web documentation) and added manpages for qubes-gpg-client, qubes-gpg-client-wrapper, and qubes-gpg-import-key. This PR is part of QubesOS/qubes-issues#2528

Readme and Manpages

---

archlinux/PKGBUILD

Adding manpages broke the Archlinux build, adding pandoc to the dependency list fixes the build.

Added pandoc to Archlinux package dependencies

---

gpg-client-wrapper

The manpage for gpg states if the output specified is '-', print to standard out. This change makes gpg-client-wrapper also respect that option.

Print to standard out if output is '-'

---

qubes.Gpg.service

Without a set expire time, notifications will hang around forever until the user clicks on them to remove them. Adding this makes them disappear after a short time as expected.

Add expire time to GPG access notifications

---

archlinux/PKGBUILD

Without this change the package builds successfully but there is a file conflict error when installing it.
I'm not sure that this is the best way to fix the issue, but I don't know enough about the builds for other distros and do not want to mess them up. Since it's used in [core-agent-linux](https://github.com/QubesOS/qubes-core-agent-linux/blob/master/archlinux/PKGBUILD#L104-L105), I assume it's OK.

Fix archlinux package - remove /var/run

---

archlinux/PKGBUILD

Replacement for https://github.com/QubesOS/qubes-app-linux-split-gpg/pull/13.
The builder-archlinux component (https://github.com/QubesOS/qubes-builder-archlinux/pull/19) needs to be changed to add this package into the local repository (qubes-vm* convention is currently followed).

archlinux: rename package to follow other distributions naming

---

qubes.Gpg.service
rpm_spec/gpg-split.spec.in
src/gpg-server.c

qubes.Gpg service may be called before X server is started in the VM.
This will result in a failure and be treated as user rejecting the
access.
Fix this by calling qubes.WaitForSession before asking for confirmation.
Fixes QubesOS/qubes-issues#4528

Wait for GUI session before asking the user for confirmation

---

qubes.GpgImportKey.service

without this, we will get the following error (on gpg 2.1):
`gpg: cannot open '/dev/tty': No such device or address`
(tested in debian 9 based VMs via manually editing `/etc/qubes-rpc/qubes.GpgImportKey` in the destination AppVM)
Closes https://github.com/QubesOS/qubes-issues/issues/5026

GpgImportKey: pass --no-tty through to gpg invocation

---

doc/qubes-gpg-client.rst

`--fixed-list-mode` in the `qubes-gpg-client` manpage is duplicated. This change fixes the typo.

remove duplicated option in manpage

---

gpg-client-wrapper

The qubes-gpg-client does not recognize the option --disable-dirmngr and thus
gives the error message "unrecognized option '--disable-dirmngr'".
In some mail clients there is little control over which arguments are passed to
gpg, in which case using split-gpg won't work due to this error message.

add ignore for --disable-dirmngr option

---

src/gpg-common.h

options whitelisted:
--no-default-recipient
--trusted-key <LONG ID>
--yes
See https://github.com/QubesOS/qubes-issues/issues/5595

Whitelist opts to get mozilla/sops compatibility

---

qubes.Gpg.service

Worked around a zenity bug that made the question window too narrow
and made the time limit be displayed as human-friendly units (days, hours,
minutes, seconds) and not just raw seconds.
fixes QubesOS/qubes-issues#5513
fixes QubesOS/qubes-issues#5514

Made split GPG permission question box nicer

---

rpm_spec/gpg-split.spec.in
tests/test_thunderbird.py

The Thunderbird 78 shipped in Debian 10 has slightly different version
(and so - UI) than then one in Fedora. Adjust test to handle both.

Adjust tests for Debian 10

---

tests/splitgpg/tests.py

Version 78.10.2 [started supporting offline master keys](https://bugzilla.mozilla.org/show_bug.cgi?id=1654893). This change
broke the configuration where the master key is offline and has no
subkeys. This is a non-default PGP key generation and hence has
little change users are in this situation.
The commit generate a master key with signing-capabilities only and a subkey for encryption
Fixes QubesOS/qubes-issues/issues/6712

tests: master key sign-only + subkey

---

tests/splitgpg/tests.py

Make remaining tests generate subkeys as well. This way all tests generate keys the same way (closer to the default attended key  generation - `gpg --gen-key`)

tests: generate w/ subkeys in remaining tests

---

tests/test_thunderbird.py

Tests like
https://openqa.qubes-os.org/tests/19954#step/TC_10_Thunderbird_fedora-34-xfce/1
were being unable to select the public key "pub.asc" from the open
file dialogue. Giving it some time, solves the issue.
fixes QubesOS/qubes-issues/issues/6812

test: fix missed clicks on "open file" dialogue

---

tests/splitgpg/tests.py
tests/test_thunderbird.py

Enigmail was the previous way of using GPG with thunderbird. Now that's built-in from Thunderbird 78+. The code had branches to support before and after that change. But now that all default templates ship a version newer than 78, the enigmail support in code is no longer needed. This PR remove that, simplifying the Thunderbird test code.

Remove enigmail test code

---

tests/test_thunderbird.py

Fixes QubesOS/qubes-issues#6817.
During the Thunderbird tests `setUp()` many times it fails randomly (see QubesOS/qubes-issues#6817). This retries particularly problematic setup steps when they fail. It's implemented via a decorator `retry_if_failed()`.
If other setups become problematic all one has to do is to make the setup step generally idempotent (see docstring of `retry_if_failed`) and add the decorator.

Tests splitgpg setup: retry if failed

---

src/gpg-common.c

If I had a GPG signature file at /tmp/sig that I wanted to verify, `qubes-gpg-client --verify /tmp/sig` would fail with a very confusing error message:
$ qubes-gpg-client --verify /tmp/sig
--verify with filename allowed only on the client side
EOF
This happened because of an off-by-one error — `untrusted_sig_path_size` includes the trailing null byte, while the return value of `snprintf` does not.  Therefore, qubes-gpg-client would think that the full file descriptor path had been written to `untrusted_sig_path`, even though the final byte would not have been, so `untrusted_sig_path` would have the value "/dev/fd/".  Alternatively, if a file descriptor greater than ten was being used, and the path to the signature file was one byte longer, the last decimal digit of the file descriptor …

Fix off-by-one in fd path replacement

---

tests/splitgpg/tests.py
tests/test_thunderbird.py

This moves one extra bit of the PGP configuration onto the `user.js` instead of relying on UI clicks (which break often).
Only the setting of the user's PGP key id was moved since the part of adding the user's key to the key manager requires some crypto stuff which does not seem to be solely doable via simple `user.js` commands.
It also removes some deprecated enigmail stuff.

Thunderbird tests: make part of the pgp setup via user.js instead of the UI

---

tests/test_thunderbird.py

Fedora-34-xfce was taking quite a bit longer. See:
https://openqa.qubes-os.org/tests/21405#step/TC_10_Thunderbird_fedora-34-xfce/1
spiritual successor to e304e584 as a testament to the ever increasing complexity of software (beyond Qubes)
closes https://github.com/QubesOS/qubes-issues/issues/7151

tests: increase search attempts for thunderbird start

---

tests/test_thunderbird.py

In Thunderbird when for various reasons would fail to send a message the program would continue with the sending message part and only fail then.
This makes makes the error message be detected at a stage at least closer to where the issue might have happened.
One example is this one: https://openqa.qubes-os.org/tests/22143#step/TC_10_Thunderbird_whonix-ws-16/2. Here the error shows as having something do with not finding the email received, but it was never sent in the first place because there was an error while sending it.

tests: earlier detection of failed message sending

---

Makefile
debian/qubes-gpg-split-tests.install
debian/rules
rpm_spec/gpg-split.spec.in
tests/Makefile
tests/whonix-clock-override.conf

Overrides the whonix bootclockrandomization's delay from +/-180 seconds to +/- 5 seconds. Won't work until https://github.com/Whonix/bootclockrandomization/pull/2 makes its way into the repos.
Whonix tests are now non-deterministically failing in two cases:
1.  [failing in splitgpg tests](https://openqa.qubes-os.org/tests/26118#step/TC_10_Thunderbird_whonix-ws-16/1). I've nailed this down to the fact that the backwards time leap is messing up the dovecot imap service we now use with thunderbird 91+ testing.
2. It also seems to be the root cause of [invalid GPG signatures](https://openqa.qubes-os.org/tests/26805#step/TC_10_Thunderbird_whonix-ws-16/3)
Having this var overridable by an env var so in the test suites we can reduce it to something like 5 seconds (already merged in …

tests: reduce whonix boot clock rand during testing

---

gpg-client-wrapper

Some code apparently relies on `--detach-sig` working.
Reported-by: Frédéric Pierret <frederic.pierret@qubes-os.org>

Translate `--detach-sig` to `--detach-sign`

---

Makefile

The Arch build was broken because there is no install-vm target in the
Makefile.

Fix the Arch build

---

src/multiplex.c

Set file descriptors to -1 after closing them, and assert that they are
in range before adding them to an FD_SET.

More robust file descriptor handling

---

gpg-client-wrapper
src/gpg-common.h

Have both the C code and wrapper script treat `-o` identically to `--output`.

Make handling of `-o` and `--output` consistent

---

src/gpg-common.c
src/gpg-server.c
tests/splitgpg/tests.py

Images in GPG keys can come from untrusted sources via
`qubes.GpgImportKey`.  Viewing them in the server is a large and
unnecessary attack surface and should not be allowed.  Programs that
access images via `--attribute-fd` are unaffected.
Tested manually; automated tests will be added later in the course of
adding unit tests to split-gpg.

Prevent GPG from launching a photo viewer     

---

src/gpg-common.c
tests/splitgpg/tests.py

The argument to --verify-options was not sanitized, and the argument to
--list-options was sanitized incorrectly.  For instance, the 'no-' forms
of list options were all rejected, breaking debsign.  Sadness ensued.
Fixes QubesOS/qubes-issues#7378.
Reported-by: Frédéric Pierret <frederic.pierret@qubes-os.org>

Fix list and verify option processing

---

src/Makefile
src/gpg-common.c
src/gpg-common.h
src/gpg-list-options.c
tests/splitgpg/tests.py

This is necessary for some programs, and avoids compatibility risks.
Hopefully this will be the last PR split-gpg1 needs.

Allow --list-options show-sig-subpackets

---

src/gpg-client.c

Previously they were silently ignored.

gpg-client: check for too many file names

---

gpg-client-wrapper
src/gpg-common.h

These are used by Mutt to suppress unwanted output.  Without them, Mutt
waits for the user to press a key before continuing.

Do not ignore -q and --quiet

---

gpg-client-wrapper

This fixes a regression if the client has been updated but the server
has not.

Emulate --quiet in terms of -q

---

tests/splitgpg/tests.py

tests: disable end-of-year message, and similar popups
